### ISSUE TITLE
[Client]처음 설치하기

### ISSUE THREAD

**Issue by hande-sof** [codestates/urimg-client#1]
### ISSUE
- Group:  `client`
- Type: `create`
- Detail: 기본 파일과 설정 완료하기

### TODO
1. [ ] 기초 파일(index.html / APP.js / index.js) 만들고 리액트 설정하기
2. [ ] 모듈 설정하고 package.json 설정하기 / gitignore 넣기
3. [ ] .env 파일로 서버 링크 일괄 수정할 수 있게 하기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1h`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `High`
