### ISSUE TITLE
[Client] 마이페이지 제작

### ISSUE THREAD

**Issue by hande-sof** [codestates/urimg-client#11]
### ISSUE
- Group:  `client`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] 네비게이터 바 연결 & 유저 프로필 props로 받아와서 랜더
2. [x] 기본적으로 로딩될 때 업로드한 사진 목록이 보이도록 / type 지정
3. [x] photo / like 클릭 시 get 요청 보내는 함수

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
