### ISSUE TITLE
[Server]  index 파일 만들기

### ISSUE THREAD

**Issue by halfkiwi90** [codestates/urimg-client#3]
### ISSUE
- Group:  `server`
- Type: `create`
- Detail: 기본설정 하고 index 파일 만들기

### TODO

1. [x]  모듈 설정하고 package.json 설정하기 / gitignore 넣기
2. [x]  .env 파일로 서버 링크 일괄 수정할 수 있게 하기
3. [x]  index.js 파일 만들기

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 1.5h`
- Group : `server`
- Sprint: `Sprint__2__`
- Urgency: `High`
