### ISSUE TITLE
[Client] 메인페이지 제작

### ISSUE THREAD

**Issue by hande-sof** [codestates/urimg-client#4]
### ISSUE
- Group:  `client`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] 메인페이지 파일 생성
2. [x] 네비게이터와 사진리스트 컴포넌트 연결해서 페이지 랜더
3. [x] fakedata 파일 만들어서 테스트용 데이터 삽입(API 참고해서 데이터 구조대로)
4. [x] 제대로 렌더되는지 체크

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `client`
- Sprint: `Sprint2`
- Urgency: `High`
