### ISSUE TITLE
[Server] S3에 이미지 업로드를 기능 추가

### ISSUE THREAD

**Issue by gibson-lee93** [codestates/urimg-client#53]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: S3에 이미지를 업로드를 위해 필요한 모듈 설치 및 설정, 업로드 기능 추가

### TODO
1. [x] 'aws-sdk'모듈 설치
2. [x] controller 폴더에 S3 기능 폴더 추가
3. [x] S3에 이미지 업로드 기능 구현
4. [x] DB Schema blob -> varchar로 변경
5. [x] DB attribute 변경

### Labels
- Estimated time: `E: 2h`
- Group : `server`
- Sprint: `Sprint__3__`
- Urgency: `High`
